version: "3.9"

services:
  # Microservicio Users
  users:
    build: ./backend/users
    ports:
      - "3001:3000"
    networks:
      - app-network

  # Microservicio Auth
  auth:
    build: ./backend/auth
    ports:
      - "3002:3000"
    networks:
      - app-network
    depends_on:
      - users

  # Frontend React
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - users
      - auth

networks:
  app-network:
    driver: bridge
